// <auto-generated />
using System;
using System.Net;
using System.Net.NetworkInformation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noema.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Noema.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NoemaDbContext))]
    [Migration("20261004080855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Noema.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Hostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("HostnameObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hostname_observed_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_assets_hostname");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_assets_last_seen_at");

                    b.ToTable("assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_assets_seen_order", "last_seen_at >= first_seen_at");
                        });
                });

            modelBuilder.Entity("Noema.Domain.AssetInterface", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<PhysicalAddress>("MacAddress")
                        .HasColumnType("macaddr")
                        .HasColumnName("mac_address");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_asset_interfaces_asset_id_no_mac")
                        .HasFilter("mac_address IS NULL");

                    b.HasIndex("MacAddress")
                        .HasDatabaseName("ix_asset_interfaces_mac_address");

                    b.HasIndex("AssetId", "MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_asset_interfaces_asset_id_mac")
                        .HasFilter("mac_address IS NOT NULL");

                    b.ToTable("asset_interfaces", null, t =>
                        {
                            t.HasCheckConstraint("ck_asset_interfaces_seen_order", "last_seen_at >= first_seen_at");
                        });
                });

            modelBuilder.Entity("Noema.Domain.InterfaceAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IPAddress>("Address")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("address");

                    b.Property<Guid>("AssetInterfaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_interface_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetInterfaceId");

                    b.ToTable("interface_addresses", null, t =>
                        {
                            t.HasCheckConstraint("ck_interface_addresses_seen_order", "last_seen_at >= first_seen_at");
                        });
                });

            modelBuilder.Entity("Noema.Domain.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IPAddress>("Address")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("address");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<PhysicalAddress>("MacAddress")
                        .HasColumnType("macaddr")
                        .HasColumnName("mac_address");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_run_id");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_observations_observed_at");

                    b.HasIndex("ScanRunId")
                        .HasDatabaseName("ix_observations_scan_run_id");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("Noema.Domain.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Probes")
                        .HasColumnType("integer")
                        .HasColumnName("probes");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("ix_scan_runs_requested_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_scan_runs_status");

                    b.ToTable("scan_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scan_runs_finished_after_started", "started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at");

                            t.HasCheckConstraint("ck_scan_runs_status_timestamps", "(status = 'Queued' AND started_at IS NULL AND finished_at IS NULL) OR (status = 'Running' AND started_at IS NOT NULL AND finished_at IS NULL) OR (status IN ('Completed', 'Failed', 'Cancelled') AND finished_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Noema.Domain.AssetInterface", b =>
                {
                    b.HasOne("Noema.Domain.Asset", null)
                        .WithMany("Interfaces")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noema.Domain.InterfaceAddress", b =>
                {
                    b.HasOne("Noema.Domain.AssetInterface", null)
                        .WithMany("Addresses")
                        .HasForeignKey("AssetInterfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noema.Domain.Observation", b =>
                {
                    b.HasOne("Noema.Domain.ScanRun", null)
                        .WithMany()
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noema.Domain.Asset", b =>
                {
                    b.Navigation("Interfaces");
                });

            modelBuilder.Entity("Noema.Domain.AssetInterface", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
